'use server';
/**
 * @fileOverview Provides a concise financial summary and key insights for a given property.
 *
 * - getFinancialInsights - A function that generates a financial summary and insights.
 * - PropertyFinancialDataInput - The input type for the getFinancialInsights function.
 * - PropertyFinancialInsightsOutput - The return type for the getFinancialInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PropertyFinancialDataInputSchema = z.object({
  propertyName: z.string().describe('The name of the property.'),
  propertyCode: z.string().describe('The unique code or ID of the property.'),
  totalInvestment: z.number().describe('The total investment cost for the property.'),
  totalConstructionCost: z.number().describe('The total cost incurred during property construction.'),
  totalRentReceived: z.number().describe('The total rent collected from the property.'),
  remainingInvestment: z
    .number()
    .describe('The amount of initial investment yet to be recovered.'),
  totalProfit: z.number().describe('The total profit generated by the property after investment recovery.'),
  maintenanceCosts: z.number().describe('The total costs incurred for maintenance and ongoing expenses.'),
  netProfit: z.number().describe('The net profit of the property (Total Rent Received - Total Investment - Maintenance Costs).'),
  costTrendsSummary: z
    .string()
    .describe('A summary of significant cost trends or recent unexpected cost overruns.'),
});
export type PropertyFinancialDataInput = z.infer<typeof PropertyFinancialDataInputSchema>;

const PropertyFinancialInsightsOutputSchema = z.object({
  summary: z.string().describe('A concise summary of the property\u0027s current financial health.'),
  keyInsights: z
    .string()
    .describe(
      'Key insights regarding profitability, remaining investment, and significant cost trends. If there are unexpected cost overruns, mention them here.'
    ),
});
export type PropertyFinancialInsightsOutput = z.infer<typeof PropertyFinancialInsightsOutputSchema>;

export async function getFinancialInsights(
  input: PropertyFinancialDataInput
): Promise<PropertyFinancialInsightsOutput> {
  return financialInsightsFlow(input);
}

const financialInsightsPrompt = ai.definePrompt({
  name: 'financialInsightsPrompt',
  input: {schema: PropertyFinancialDataInputSchema},
  output: {schema: PropertyFinancialInsightsOutputSchema},
  prompt: `You are an expert financial analyst specializing in real estate investment. Your task is to analyze the financial data for a property and provide a concise summary and key insights.

Property Name: {{{propertyName}}} (Code: {{{propertyCode}}})

Financial Data:
- Total Investment: $ {{{totalInvestment}}}
- Total Construction Cost: $ {{{totalConstructionCost}}}
- Total Rent Received: $ {{{totalRentReceived}}}
- Remaining Investment: $ {{{remainingInvestment}}}
- Total Profit: $ {{{totalProfit}}}
- Maintenance Costs: $ {{{maintenanceCosts}}}
- Net Profit: $ {{{netProfit}}}

Cost Trends Summary: {{{costTrendsSummary}}}

Based on the data provided, please generate:
1. A concise summary of the property's financial health.
2. Key insights regarding its profitability, remaining investment, and any significant cost trends. Highlight any unexpected cost overruns if mentioned in the cost trends summary.
`,
});

const financialInsightsFlow = ai.defineFlow(
  {
    name: 'financialInsightsFlow',
    inputSchema: PropertyFinancialDataInputSchema,
    outputSchema: PropertyFinancialInsightsOutputSchema,
  },
  async input => {
    const {output} = await financialInsightsPrompt(input);
    return output!;
  }
);
